/* tslint:disable */
/* eslint-disable */
/**
 * goormbread api
 * 구름빵 API입니다.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PatchUserPadInformationDto
 */
export interface PatchUserPadInformationDto {
    /**
     * 사용자 게임 커맨드 JSON
     * @type {object}
     * @memberof PatchUserPadInformationDto
     */
    user_game_command: object;
}

/**
 * Check if a given object implements the PatchUserPadInformationDto interface.
 */
export function instanceOfPatchUserPadInformationDto(value: object): value is PatchUserPadInformationDto {
    if (!('userGameCommand' in value) || value['userGameCommand'] === undefined) return false;
    return true;
}

export function PatchUserPadInformationDtoFromJSON(json: any): PatchUserPadInformationDto {
    return PatchUserPadInformationDtoFromJSONTyped(json, false);
}

export function PatchUserPadInformationDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchUserPadInformationDto {
    if (json == null) {
        return json;
    }
    return {
        
        'user_game_command': json['userGameCommand'],
    };
}

export function PatchUserPadInformationDtoToJSON(value?: PatchUserPadInformationDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'userGameCommand': value['user_game_command'],
    };
}

