/* tslint:disable */
/* eslint-disable */
/**
 * goormbread api
 * 구름빵 API입니다.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SaveUserDto
 */
export interface SaveUserDto {
    /**
     * userId
     * @type {string}
     * @memberof SaveUserDto
     */
    userId: string;
    /**
     * password
     * @type {string}
     * @memberof SaveUserDto
     */
    password: string;
    /**
     * nickname
     * @type {string}
     * @memberof SaveUserDto
     */
    nickname: string;
}

/**
 * Check if a given object implements the SaveUserDto interface.
 */
export function instanceOfSaveUserDto(value: object): value is SaveUserDto {
    if (!('userId' in value) || value['userId'] === undefined) return false;
    if (!('password' in value) || value['password'] === undefined) return false;
    if (!('nickname' in value) || value['nickname'] === undefined) return false;
    return true;
}

export function SaveUserDtoFromJSON(json: any): SaveUserDto {
    return SaveUserDtoFromJSONTyped(json, false);
}

export function SaveUserDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): SaveUserDto {
    if (json == null) {
        return json;
    }
    return {
        
        'userId': json['userId'],
        'password': json['password'],
        'nickname': json['nickname'],
    };
}

export function SaveUserDtoToJSON(value?: SaveUserDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'userId': value['userId'],
        'password': value['password'],
        'nickname': value['nickname'],
    };
}

