name: Update docker image and helm chart

on:
    pull_request:
        branches:
            - develop
        types: [closed]



jobs:
        
    docker-image-build-and-test:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout code
          uses: actions/checkout@v2
        
        - name: Login to Docker
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_SECRET }}

        - name: Build Docker image
          run: docker build -t geonhyukseo/goormfront:${{ github.sha }} .

        - name: Push Docker image
          run: docker push geonhyukseo/goormfront:${{ github.sha }}

    web-helm-update:
      runs-on: ubuntu-latest
      needs: docker-image-build-and-test

      steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Checkout Helm chart repository
          uses: actions/checkout@v2
          with:
            repository: GoormBread/web-helm
            token: ${{ secrets.GH_PAT }}
            path: web-helm
        
        - name: Install yq
          run: |
            sudo apt-get update -y
            sudo apt-get install -y jq
        
        - name: Update values.yaml
          run: |
            cd web-helm
            yq eval '.frontend.image.tag = "${{ github.sha }}"' -i ./web-helm/values.yaml
        
        - name: Setup Helm
          uses: azure/setup-helm@v1
          with:
            version: 'v3.5.4'

        - name: Package Web Helm chart
          run: |
            cd web-helm
            helm package web-helm/
            helm repo index .

        - name: Commit and Push changes
          env:
            GH_PAT: ${{ secrets.GH_PAT }}
          run: |
            cd web-helm
            git config --global user.email "sgh4123@naver.com"
            git config --global user.name "SeoGeonhyuk"
            git add .
            git commit -m "Update front image tag to ${{ github.sha }} and package Helm chart"
            git push https://x-access-token:${GH_PAT}@github.com/GoormBread/web-helm.git main
      

            